steps:

- id: dev-init
  uses: docker://alpine/git:v2.24.3
  runs: [sh]
  args:
  - -c
  - |
    set -e
    git clone \
      --recursive \
      --depth 1 \
      --shallow-submodules \
      --branch luminous \
      https://github.com/ceph/ceph

    ln -s ../../../src ceph/src/cls/tabular

    echo "add_subdirectory(tabular)" >> ceph/src/cls/CMakeLists.txt

- id: build
  uses: docker://uccross/skyhookdm-builder:luminous
  runs: [bash]
  env:
    CMAKE_FLAGS: "-DBOOST_J=4 -DWITH_PYTHON3=OFF"
    BUILD_THREADS: "4"
  args: [scripts/build.sh]

- id: build-rook-img
  uses: docker://docker:19.03.10
  args:
  - build
  -   --build-arg=CEPH_RELEASE=luminous
  -   --tag=uccross/skyhookdm-ceph:v12.2.12
  -   --file=docker/Dockerfile.release
  -   .

- id: test
  uses: docker://uccross/skyhookdm-ceph:luminous
  skip_pull: true
  runs: [bash]
  env:
    LD_LIBRARY_PATH: /usr/lib64/ceph
  args: [scripts/run_tests.sh]
